repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: tflint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.47.0
    hooks:
      - id: terraform_tfsec
